# Generated by Django 4.2.3 on 2023-10-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedfires',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
