# Generated by Django 4.2.3 on 2023-10-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_reportedfires_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedfires',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportedfires',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
