# Generated by Django 4.2.3 on 2023-10-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_reportedfires_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='official',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
