# Generated by Django 4.2.3 on 2023-10-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_employee_official_alter_stations_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedfires',
            old_name='StationPlacedId',
            new_name='StationPlaced',
        ),
    ]
