# Generated by Django 4.2.3 on 2023-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_stationplacedid_reportedfires_stationplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='IdNumber',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
